// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository.Context;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250111205133_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductUser", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("ProductsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ProductUser");
                });

            modelBuilder.Entity("backend.Abstraction.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Toys"
                        });
                });

            modelBuilder.Entity("backend.Abstraction.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Description of Product 1",
                            Discount = 5m,
                            ImageUrl = "https://example.com/product1.jpg",
                            Name = "Product 1",
                            Price = 101m,
                            ProductCode = "P001"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Description = "Description of Product 2",
                            Discount = 10m,
                            ImageUrl = "https://example.com/product2.jpg",
                            Name = "Product 2",
                            Price = 102m,
                            ProductCode = "P002"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            Description = "Description of Product 3",
                            Discount = 0m,
                            ImageUrl = "https://example.com/product3.jpg",
                            Name = "Product 3",
                            Price = 103m,
                            ProductCode = "P003"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            Description = "Description of Product 4",
                            Discount = 5m,
                            ImageUrl = "https://example.com/product4.jpg",
                            Name = "Product 4",
                            Price = 104m,
                            ProductCode = "P004"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Description of Product 5",
                            Discount = 10m,
                            ImageUrl = "https://example.com/product5.jpg",
                            Name = "Product 5",
                            Price = 105m,
                            ProductCode = "P005"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Description of Product 6",
                            Discount = 0m,
                            ImageUrl = "https://example.com/product6.jpg",
                            Name = "Product 6",
                            Price = 106m,
                            ProductCode = "P006"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Description of Product 7",
                            Discount = 5m,
                            ImageUrl = "https://example.com/product7.jpg",
                            Name = "Product 7",
                            Price = 107m,
                            ProductCode = "P007"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Description of Product 8",
                            Discount = 10m,
                            ImageUrl = "https://example.com/product8.jpg",
                            Name = "Product 8",
                            Price = 108m,
                            ProductCode = "P008"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "Description of Product 9",
                            Discount = 0m,
                            ImageUrl = "https://example.com/product9.jpg",
                            Name = "Product 9",
                            Price = 109m,
                            ProductCode = "P009"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Description of Product 10",
                            Discount = 5m,
                            ImageUrl = "https://example.com/product10.jpg",
                            Name = "Product 10",
                            Price = 110m,
                            ProductCode = "P010"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Description of Product 11",
                            Discount = 10m,
                            ImageUrl = "https://example.com/product11.jpg",
                            Name = "Product 11",
                            Price = 111m,
                            ProductCode = "P011"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Description of Product 12",
                            Discount = 0m,
                            ImageUrl = "https://example.com/product12.jpg",
                            Name = "Product 12",
                            Price = 112m,
                            ProductCode = "P012"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "Description of Product 13",
                            Discount = 5m,
                            ImageUrl = "https://example.com/product13.jpg",
                            Name = "Product 13",
                            Price = 113m,
                            ProductCode = "P013"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "Description of Product 14",
                            Discount = 10m,
                            ImageUrl = "https://example.com/product14.jpg",
                            Name = "Product 14",
                            Price = 114m,
                            ProductCode = "P014"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Description = "Description of Product 15",
                            Discount = 0m,
                            ImageUrl = "https://example.com/product15.jpg",
                            Name = "Product 15",
                            Price = 115m,
                            ProductCode = "P015"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Description of Product 16",
                            Discount = 5m,
                            ImageUrl = "https://example.com/product16.jpg",
                            Name = "Product 16",
                            Price = 116m,
                            ProductCode = "P016"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "Description of Product 17",
                            Discount = 10m,
                            ImageUrl = "https://example.com/product17.jpg",
                            Name = "Product 17",
                            Price = 117m,
                            ProductCode = "P017"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "Description of Product 18",
                            Discount = 0m,
                            ImageUrl = "https://example.com/product18.jpg",
                            Name = "Product 18",
                            Price = 118m,
                            ProductCode = "P018"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            Description = "Description of Product 19",
                            Discount = 5m,
                            ImageUrl = "https://example.com/product19.jpg",
                            Name = "Product 19",
                            Price = 119m,
                            ProductCode = "P019"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Description = "Description of Product 20",
                            Discount = 10m,
                            ImageUrl = "https://example.com/product20.jpg",
                            Name = "Product 20",
                            Price = 120m,
                            ProductCode = "P020"
                        });
                });

            modelBuilder.Entity("backend.Abstraction.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Street, City",
                            Contact = "1234567890",
                            Email = "alice@example.com",
                            Name = "Alice",
                            Password = "password1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Avenue, City",
                            Contact = "1234567891",
                            Email = "bob@example.com",
                            Name = "Bob",
                            Password = "password2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Boulevard, City",
                            Contact = "1234567892",
                            Email = "charlie@example.com",
                            Name = "Charlie",
                            Password = "password3"
                        },
                        new
                        {
                            Id = 4,
                            Address = "101 Main St, City",
                            Contact = "1234567893",
                            Email = "david@example.com",
                            Name = "David",
                            Password = "password4"
                        },
                        new
                        {
                            Id = 5,
                            Address = "202 Elm St, City",
                            Contact = "1234567894",
                            Email = "eve@example.com",
                            Name = "Eve",
                            Password = "password5"
                        });
                });

            modelBuilder.Entity("ProductUser", b =>
                {
                    b.HasOne("backend.Abstraction.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Abstraction.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Abstraction.Models.Product", b =>
                {
                    b.HasOne("backend.Abstraction.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("backend.Abstraction.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
